### PR TITLE
Expose the gRPC port and fix rendering of CIDR block list for loadBalancerSourceRanges

### PR DESCRIPTION
**Pull request by alexandrujieanu**
Closes https://github.com/uptrace/helm-charts/issues/6

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks :+1:

**Comment by mkobetic** [comment]
I think this needed also rolling the chart version and tagging the released commit. Otherwise `helm pull --version 1.3.1` pulls the old version without the grpc port.

**Comment by vmihailenco** [comment]
@mkobetic right, but we are almost ready to release v1.4 so I will tag v1.4 in a couple of days...

**Comment by mkobetic** [comment]
I see, I wasn't sure what was going to happen. I can definitely wait for the release. Thank you!

**Pull request merged**
